### ISSUE TITLE
Feed - Criar tela de inicial

### ISSUE THREAD

**Issue by ewertondias** [estergcarvalho/codeconnect-ui#3]
#### Descrição
Criar tela de feed do usuário

#### Objetivo
Ter a estrutura inicial da tela princial de feed

#### Escopo
- Menu deve ser uma barra suspensa e fixa no em cima
- Rodapé deve ser uma barra maior fixa no embaixo
- Template de feed no meio da página
  - Foto redonda a esquerda
  - Nome na frente da foto
  - Embaixo do nome colocar um texto que servirá de data ex: 1 hora atrás
  - Container do post ser "flutuante" e ter borda arredondada
    - Referência do topo do container de post imagem em anexo 1.0
    - Referência do rodapé do container de post imagem em anexo 1.1

#### Referência de layout
* Ver tema dark
https://prium.github.io/falcon/v3.20.0/app/social/feed.html

#### Critérios de aceite
Cores seguindo paleta pré definida
Tema Dark

**Comment by ewertondias** [comment]
![Image](https://github.com/estergcarvalho/codeconnect-ui/assets/1419523/b8fb1240-21d5-405f-9b96-9f372abcc444)

**Comment by ewertondias** [comment]
1.1 - Referência do rodapé do container do post

![Image](https://github.com/estergcarvalho/codeconnect-ui/assets/1419523/56f0dcec-fec2-4402-af5d-a0dd720e78c5)

**Comment by estergcarvalho** [comment]
https://prium.github.io/falcon/v3.20.0/app/social/feed.html
